### PR TITLE
Cleanup env

### PR DESCRIPTION
**Pull request by brianspiering**

### CODE REVIEW

**Comment by brianspiering** [comment]
I improve the setup scripts. Please have a look 👀

**Comment by stroxler** [comment]
Just hooked up Circle

The first build failed due to some silly stuff, I patched config.yml
Probably heading home soon, but I'll check back in later tonight

**Comment by stroxler** [comment]
Checks passed!

Going to squash my changes

**Comment by stroxler** [comment]
Looks good to me, merging

**Pull request merged**
